[package]
name = "b4n-list"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "./lib.rs"

[dependencies]
crossterm = { workspace = true }
k8s-openapi = { workspace = true }
